veertly/app

src/Components/EventSession/AvailableTab.js

Fix available presence

---

.github/workflows/master.yml
.github/workflows/stage.yml
src/Components/EditEventSession/EditEventSessionForm.js
src/Components/EventSession/CurrentCallActions.js
src/Modules/eventSessionOperations.js
src/Modules/eventsOperations.js

Fix conversation duration and checking the existance of an event code

---

functions/index.js
src/Containers/EventSession/EventSessionContainer.js

Fix issue with the ghost conversations

---

src/Containers/EventSession/EventSessionContainer.js

Remove warning

---

src/Components/EditEventSession/EditEventSessionForm.js

Fix issue with the Description editor

---

package.json
src/Components/EventShow/EventPage.js
src/Components/MUIAddToCalendar.js

Fix issue with description of the event

---

src/Components/EditEventSession/EditEventSessionForm.js
src/Components/EventShow/EventPage.js
src/Modules/eventSessionOperations.js

Fix issue on the edit event form

---

package.json
src/Components/EditEventSession/EditEventSessionForm.js
src/Components/EventShow/EventPage.js
src/Components/MUIAddToCalendar.js
src/Containers/EventSession/EventSessionContainer.js

Revert "Improve empty networking page, event page and success message"

---

src/Components/Event/EventRegistrationForm.js

Fix issue with some fields on the registration

---

src/App.js
src/Components/EventSession/AvailableTab.js
src/Components/EventSession/FilterAttendeesDialog.js
src/Redux/eventSession.js

- Update filters UI to use Autocomplete
- Use redux store to manage the filters selected

Update filters UI

---

package.json
src/Components/Chat/ChatMessage.js
src/Components/Event/EditEventSessionForm.js
src/Components/Event/EventPage.js
src/Components/EventSession/AvailableTab.js
src/Components/EventSession/JoinConversationDialog.js
src/Components/EventSession/JoinParticipantDialog.js
src/Components/Misc/UserAvatar.js
src/Config/constants.js
src/Containers/EventSession/ConferenceRoomContainer.js
src/Containers/EventSession/EventSessionContainer.js
src/Modules/userOperations.js
src/Redux/dialogs.js

Join participant dialog from chat and event is over message

---

.eslintrc
package.json
src/App.js
src/Components/Chat/ChatMessagesPane.js
src/Components/Chat/ChatPane.js
src/Components/Event/ShareEventDialog.js
src/Components/EventSession/AvailableTab.js
src/Components/EventSession/FilterAttendeesDialog.js
src/Config/routes.js
src/Containers/EventSession/EventSessionContainer.js
src/registerServiceWorker.js

- Make correct share URL
- Add filters and make conversation buttons on the main stage

Fix bugs from trello board

---

.eslintrc
src/Components/Chat/ChatMessage.js
src/Components/EditProfile/EditProfileForm.js
src/Components/Event/EventRegistrationForm.js
src/Containers/EventSession/EventPageContainer.js

- Add a star on T&C when it is not selected
- Open user profile on name click in the chat.

Fix the remaining trello bug

---

src/index.js
src/registerServiceWorker.js

Unregister the service worker.
We need to test it on the stage.

Unregister service worker

---

src/Components/EventSession/AvailableTab.js
src/Components/EventSession/ParticipantCard.js
src/Components/Misc/Flag.js

Participant's flags on the attendees' list

---

.editorconfig
.eslintrc
.github/workflows/test.yml
package.json
src/Components/EventSession/EventSessionTabs.js
src/Components/EventSession/FacebookPlayer.js
src/Components/EventSession/VideoPlayer.js
src/Components/EventSession/YoutubePlayer.js
src/Containers/EventSession/ConferenceRoomContainer.js
src/Containers/EventSession/EventSessionContainer.js
src/Containers/EventSession/JitsiContext.js
src/Containers/EventSession/NetworkingRoomContainer.js
src/Containers/EventSession/SmallPlayerContainer.js
src/Hooks/useJitsi.js
src/Utils.js
src/index.js
src/registerServiceWorker.js

Feature PiP on test environment

---

src/Components/EditProfile/ProfileChips.js
src/Components/EventSession/AvailableTab.js
src/Components/EventSession/ConversationsTab.js
src/Components/EventSession/CurrentCallActions.js
src/Components/EventSession/EventSessionTabs.js
src/Components/EventSession/EventSessionTopbar.js
src/Components/EventSession/GroupAvatars.js
src/Components/EventSession/JoinConversationDialog.js
src/Components/EventSession/JoinParticipantDialog.js
src/Components/EventSession/JoinRoomDialog.js
src/Components/EventSession/SideMenuIcons.js
src/Components/Misc/Flag.js
src/Components/Misc/ParticipantAvatar.js
src/Helpers/detectEmojiSupport.js
src/Redux/eventSession.js

Several fixes

---

src/Components/Event/EditEventSessionForm.js
src/Components/Misc/Flag.js
src/index.js

verify event id before checking if it exists

---

.eslintrc
functions/index.js
public/firebase-messaging-sw.js
src/App.js
src/Containers/EventSession/EventSessionContainer.js
src/Containers/EventSession/JitsiContext.js
src/Containers/EventSession/PasswordProtectedEventSessionContainer.js
src/Modules/features.js
src/Modules/firebaseApp.js
src/Redux/eventSession.js
src/registerServiceWorker.js

- Enable passwords in events.
- Use app callable firebase functions

feat: add login firebase function and password protected container

---

functions/index.js
src/App.js
src/Components/EditProfile/EditProfileForm.js
src/Components/Event/EventPage.js
src/Config/routes.js
src/Containers/EventSession/PasswordProtectedEventSessionContainer.js
src/Containers/LoginContainer.js
src/Modules/eventSessionOperations.js
src/Modules/firebaseApp.js

- Improve the password dialog UI and add validation

Add validation to password dialog

---

.prettierrc
src/Components/Event/EditEventSessionForm.js
src/Containers/EventSession/ConferenceRoomContainer.js
src/Containers/EventSession/EventSessionContainer.js
src/Containers/EventSession/NetworkingRoomContainer.js
src/Containers/EventSession/SmallPlayerContainer.js
src/Containers/Layouts/CenteredLayout.js
src/Helpers/wdyr.js
src/Modules/eventSessionOperations.js
src/Modules/jitsi.js

Allow custom jitsi for each event

---

public/index.html
src/Components/EventSession/EventSessionTopbar.js
src/Config/routes.js
src/Containers/EventSession/ConferenceRoomContainer.js
src/Containers/EventSession/EventSessionContainer.js
src/Modules/userOperations.js

Crisp chat + hangup conference redirect

---

src/Modules/features.js

Patch error on checking if feature exist

---

src/Containers/EventSession/SmallPlayerContainer.js
src/Utils.js

- Disable dragging when the cursor on video player.
- Increase the Toolbar height to give more dragging area and a buffer for drag cancel
- Add a border on player
- Increase little height to compensate for the player.

Fix player dragging issues

---

src/Components/Event/EditEventSessionForm.js

Fix issues on the event creation form and other improvements

---

src/Components/Event/EditEventSessionForm.js

fix issue with space on the event url

---

package.json
src/App.js
src/Components/Event/EventPage.js
src/Components/HomeComponent.js
src/Components/Shared/CompatibilityDialog.js
src/Components/Shared/CompatibilityInfo.js
src/Components/Shared/MarginProvider.js
src/Containers/EventSession/EventPageContainer.js
src/Containers/EventSession/PasswordProtectedEventSessionContainer.js
src/Containers/HomePage.js
src/Hooks/useDeviceDetect.js
src/Redux/account.js

- Add alert label in home page and event page
- Add dialog on the live event page
- Revert login fix

Add alert label and dialog for compatibility

---

src/Components/EventSession/ArchiveRoomDialog.js
src/Components/EventSession/ConversationsTab.js
src/Components/EventSession/CurrentCallActions.js
src/Components/EventSession/EditRoomDialog.js
src/Components/EventSession/JoinRoomDialog.js
src/Components/EventSession/RoomArchivedDialog.js
src/Components/EventSession/RoomCard.js
src/Containers/EventSession/EventSessionContainer.js
src/Modules/eventSessionOperations.js
src/Redux/dialogs.js
src/Redux/store.js

Edit and archive rooms

---

src/App.js
src/Components/EventSession/ArchiveRoomDialog.js
src/Components/EventSession/RoomArchivedDialog.js
src/Components/MUIAddToCalendar.js
src/Components/Misc/CloseableSnackbar.js

New archive messages

---

src/Containers/EventSession/EventSessionContainer.js

Fix text over sections

---

src/Components/EventSession/EventSessionTopbar.js
src/Containers/EventSession/EventSessionContainer.js

Remove attendees list

---

src/Components/Chat/ChatMessagesPane.js
src/Components/EventSession/LocationPanes/AttendeesPane.js
src/Containers/EventSession/ConferenceRoomContainer.js
src/Containers/EventSession/EventSessionContainer.js
src/Modules/jitsi.js

last fixes before launch of new ui

---

src/Components/EventSession/PresenceSwitch.js
src/Helpers/participantsHelper.js
src/Redux/eventSession.js

Default presence to available

---

.github/workflows/master.yml

Force triggering of master deployment

---

package.json
src/Components/Chat/SendMessagePane.js

- Add emojis keyboard
- Make it initialize once.
- Customize it acc to the theme.

Add emoji support

---

src/Components/Chat/ChatMessage.js
src/Components/Chat/SendMessagePane.js
src/Containers/EventSession/EventSessionContainerWrapper.js
src/Contexts/ChatDraftMessageContext.js
src/Providers/ChatDraftMessageProvider.js

- Abstract messages using context
- Change the opacity of chat message color

Save messages across tab switches

---

src/Components/EventSession/Polls/PollsPane.js

Update 0votes text

---

src/Components/Chat/SendMessagePane.js

- move the focus when emoji window is canceled
- don't close the emojis when clicking on the search

Remove bug introduced due to lazy initialization

---

src/Components/EventSession/CreateRoomDialog.js
src/Components/EventSession/VerticalNavBar.js
src/Config/constants.js

- Fix saving old rooms
- Fixing the limit of 3 participants per conversation
- Do not automatically enter the main stage when on the lobby

Fixing issues (rooms, limit participants and main stage pane)

---

package.json
yarn.lock

mui-rte update

---

credits.md
src/Components/EventSession/BroadcastMessages/BroadcastDialogManager.js
src/Components/EventSession/BroadcastMessages/BroadcastMessagesPane.js
src/Components/EventSession/BroadcastMessages/CreateBroadcastDialog.js
src/Components/EventSession/ParticipantBroadcastDialogContainer.js
src/Components/Misc/Label.js
src/Modules/broadcastOperations.js

Broadcast message

---

src/Components/EventSession/ParticipantBroadcastDialogContainer.js
src/Components/EventSession/VerticalNavBar.js
src/Containers/EventSession/EventSessionContainer.js

fix issue with backstage and close on broadcast message

---

src/Components/EventSession/VerticalNavBar.js

Fix issue visibility backstage

---

src/Components/EventSession/AudioVideoCheckDialog.js
src/Components/EventSession/DevicesOptions.js
src/Containers/EventSession/EventSessionContainer.js
src/Containers/EventSession/NetworkingRoomContainer.js

- Improve layout little bit
- Join event => join call In case of networking tab
- Join event => join room in rooms tab
- disable video when the video is muted in the dialog
- remove extra room in the dialog
- add need help
- reflect audio and video devices change in the dialog itself

Technical check improvements
